### ISSUE TITLE
bfac docker image

### ISSUE THREAD

**Issue by giper45** [mazen160/bfac#11]
Hi @mazen160 , thanks for the tool! 
I have created a docker image to use it:
https://github.com/giper45/bfac-docker-image  
If you want, you could add it to documentation or move Dockerfile in your project. 
Regards.

**Comment by mazen160** [comment]
Hi @giper45!

Thanks! I have merged it into bfac repo. Nice one!
I also change the python template to alpine, should be easier to deploy there since the tool doesn't have much requirements, and it should be faster to pull the alpine image.

Best,
Mazin
