### ISSUE TITLE
issue while running your tool on windows

### ISSUE THREAD

**Issue by workfast108** [mazen160/bfac#4]
Hi Mazen,

I checked out your tool on github , it look good for what i actually wanted, but the problem now is i can't get it working on windows PC actually , i have attached the error i encounter on windows. Kindly give the command to run the tool on window , i have already gotten the requirements install properly , still can not  get  the tool working.

Warm Regards
Dere Sewa
![issue](https://cloud.githubusercontent.com/assets/24754100/23346243/604cb854-fc4d-11e6-80a8-0eec85d11470.PNG)

**Comment by mazen160** [comment]
Hi @workfast108,

You can run BFAC normally in Windows using the following command:

`
python C:\bfac-master\bfac\bfac.py -h
`

Best,
Mazin
